baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'module'

[markup]
    highlight.noClasses = false

[params]
    moduleName = 'Web application development'
    moduleCode = 'CTEC2712'

