baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'module'

[markup.highlight]
    _merge = "shallow"

[params]
    moduleName = 'Web application development'
    moduleCode = 'CTEC2712'
    customcss = ['colours.css']

