baseURL = 'https://ggstuart.github.io/web-application-development'
theme = 'module'

[languages]
    [languages.en]
        locale = "en-gb"


[markup]
    [markup.highlight]
        _merge = "shallow"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.renderHooks]
            [markup.goldmark.renderHooks.link]
                useEmbedded = "fallback"

[params]
    moduleName = 'Web application development'
    moduleCode = 'CTEC2712'
    customcss = ['colours.css', 'mdn.css']

